### PR TITLE
fix (jkube-kit-spring-boot) : Directly read `layers.idx` file to get layers information

### LINKED ISSUE #3228: Springboot 3.3.1 breaks jkube openshift plugin
### Describe the bug

springboot 3.3.1 comes with a new layertool that breaks jkube openshift plugin. Projects upgrading to springboot 3.3.1 will get the following error when they run oc:build command:

`[ERROR] Failed to execute goal org.eclipse.jkube:openshift-maven-plugin:1.16.2:build (default-cli) on project layered-jar-3.3.1-bug: Failed to execute the build: Unable to build the image using the OpenShift build service: Assemblies with more than one layer require a proper id for each layer -> [Help 1]
`

The core of the issue is the new layertool is that there is an extra message accompanied by a new line in the output when command `java -Djarmode=layertools -jar xxx.jar list` is run

```
❯ java -Djarmode=layertools -jar target/layered-jar-3.3.1-bug-0.0.1-SNAPSHOT.jar list
Warning: This command is deprecated. Use '-Djarmode=tools list-layers' instead.

dependencies
spring-boot-loader
snapshot-dependencies
application
```

Jkube identifies the empty line as an individual layer without an id and fails with error message provided above. Additionally, JKube identifies any line output in the layertool as a layer. In our case, layer tool has additional lines in the output that are picked as layers erroneously. Here is a sample layertool output on our project:

```
❯ java -Djarmode=layertools -jar payment-service-0.0.1-SNAPSHOT.jar list
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
SLF4J(W): Class path contains multiple SLF4J providers.
SLF4J(W): Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@52a86356]
SLF4J(W): Found provider [org.apache.logging.slf4j.SLF4JServiceProvider@5ce81285]
SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J(I): Actual provider is of type [ch.qos.logback.classic.spi.LogbackServiceProvider@52a86356]
Warning: This command is deprecated. Use '-Djarmode=tools list-layers' instead.

dependencies
spring-boot-loader
snapshot-dependencies
application
```

in the above case, JKube creates the following 8 layers where as only layer 4-7 are applicable.

1. Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2. Warning: This command is deprecated. Use '-Djarmode=tools list-layers' instead.
3. 
4. dependencies
5. spring-boot-loader
6. snapshot-dependencies
7. application

### Eclipse JKube version

1.16.2

### Component

OpenShift Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

run `mvn package oc:build` on the project in https://github.com/Farzad407/layered-jar-3.3.1-bug repository.

### Expected behavior

image build task to succeed.

### Runtime

OpenShift

### Kubernetes API Server version

1.25.3

### Environment

macOS

### Eclipse JKube Logs

```shell
[INFO] --- oc:1.16.2:build (default-cli) @ layered-jar-3.3.1-bug ---
[INFO] oc: Using OpenShift build with strategy Docker
[INFO] oc: Running generator spring-boot
[INFO] oc: spring-boot: Using Docker image quay.io/jkube/jkube-java:0.0.23 as base / builder
[INFO] oc: Spring Boot layered jar detected
[ERROR] oc: Failed to execute the build [Unable to build the image using the OpenShift build service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.364 s
[INFO] Finished at: 2024-07-15T15:40:45-04:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "prodprofile" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.eclipse.jkube:openshift-maven-plugin:1.16.2:build (default-cli) on project layered-jar-3.3.1-bug: Failed to execute the build: Unable to build the image using the OpenShift build service: Assemblies with more than one layer require a proper id for each layer -> [Help 1]
```

### Sample Reproducer Project

https://github.com/Farzad407/layered-jar-3.3.1-bug

### Additional context

maven version 3.9.6 but it should be reproducible across all maven versions.

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #3228

Till now we were executing layertools list command to extract layer related information for Spring Boot Layered jar. This has started causing problems in Spring Boot 3.3.x where we're getting additional deprecation warning that's breaking behavior of SpringBootGenerator. Additionally, layertools command has become deprecated in Spring Boot 3.3.x

Instead of relying on layertools command, directly read layers.idx file present in layered jar to extract list of layers. `layers.idx` file format seems to be consistent across previous Spring Boot versions. You can see it's spec in [LayersIndex.java](https://github.com/spring-projects/spring-boot/blob/3648f5f494e6b5bb010bb7f881eb748cbc0f8cc5/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/boot/loader/tools/LayersIndex.java#L35) : 

> Index describing the layer to which each entry in a jar belongs. Index files are simple text files that should be read from top to bottom. Each file defines the layers and their content. Layer names are written as quoted strings prefixed by a dash space  `"- "` and with a colon `":"` suffix. Layer content is either a file or directory name written as a quoted string prefixed by space dash space `"  - "`. A directory name ends with`/`, a file name does not. When a directory name is used it means that all files inside that directory are in the same layer.

> Index files are designed to be compatible with YAML and may be read into a list of `Map<String, List<String>>` instances.

Existing tests verify that the SpringBootLayeredJar works as expected even after making this change.

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] My code follows the style guidelines of this project
 - [X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [X] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3236 (_2024-07-17T16:56:04Z_)

:gear: [JKube E2E Tests (9978306809)](https://github.com/eclipse-jkube/ci/actions/runs/9978306809) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3236)](https://github.com/eclipse-jkube/ci/actions/runs/9978306809/job/27574894382)

**Comment by rohanKanojia** [comment]
Not sure why openshift CI is failing, same test is passing locally: 

Screenshot_20240718_164304

**Review by manusa — COMMENTED** [review]
Looks OK, but are there any tests to verify this?

It seems like the prior mechanism didn't have tests either

File: jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/SpringBootLayeredJar.java [hunk 1]
```diff
@@ -65,10 +68,16 @@ public String getMainClass() {
   }
 
   public List<String> listLayers() {
-    final LayerListCommand layerListCommand = new LayerListCommand(kitLogger, layeredJar);
-    try {
-      layerListCommand.execute();
-      return layerListCommand.getLayers();
+    try (JarFile jarFile = new JarFile(layeredJar)) {
+      String layerFileContent = IOUtils.toString(jarFile.getInputStream(jarFile.getEntry("BOOT-INF/layers.idx")), StandardCharsets.UTF_8);
+      List<Map<String, List<String>>> layers = Serialization.unmarshal(layerFileContent, List.class);
```
Comment (manusa) [inline jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/SpringBootLayeredJar.java:73]: Why aren't we using Serialization.unmarshal from InputSream?

Comment (rohanKanojia) [reply jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/SpringBootLayeredJar.java:73]: oh, okay. let me use that method.

**Comment by manusa** [comment]
> > It seems like the prior mechanism didn't have tests either
> 
> We have SpringBootLayeredJarTest that verifies layer list with real jar and fake jar (created within test)
> 
> https://github.com/eclipse-jkube/jkube/blob/9fb108562e89b508e50b571e28bba8db3433388b/jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/SpringBootLayeredJarTest.java#L91
> 
> https://github.com/eclipse-jkube/jkube/blob/9fb108562e89b508e50b571e28bba8db3433388b/jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/SpringBootLayeredJarTest.java#L114

OK, that's cool. It means that regardless of the underlying implementation, the black-boxed test is working as expected :tada:

**Comment by rohanKanojia** [comment]
Yes, on top of that we also have [CompleteOcDockerLayersDisabledITCase](https://github.com/eclipse-jkube/jkube-integration-tests/blob/main/it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteOcDockerLayersDisabledITCase.java) to verify that plugin works with or without layer functionality

**Review by manusa — APPROVED** [review]
LGTM, thx!
