### PR TITLE
fix SpringBootWatcherIntegrationTest on macos

### LINKED ISSUE #3009: SpringBootWatcherIntegrationTest fails on MacOS
### Describe the bug

Test case `withAllRequirementsShouldStartWatcherProcess` from class `SpringBootWatcherIntegrationTest` is failing with a message indicating a mismatch between actual and wanted arguments to the process. Here is the complete message:
```
Argument(s) are different! Wanted:
runtime.exec(
    <custom argument matcher>
);
-> at java.base/java.lang.Runtime.exec(Runtime.java:453)
Actual invocations have different arguments:
runtime.exec(
    ["/Users/{my username}/.sdkman/candidates/java/17.0.5-amzn/bin/java", "-cp", "/private/var/folders/5q/fb9_qmc91h76mqsnyqxnf7x00000gn/T/junit14501484792843800327/target/spring-boot-lib.jar:/private/var/folders/5q/fb9_qmc91h76mqsnyqxnf7x00000gn/T/junit14501484792843800327/target/spring-boot-devtools.jar", "-Dspring.devtools.remote.secret=this-is-a-test", "org.springframework.boot.devtools.RemoteSpringApplication", "http://localhost:59169"]
);
```
This is because the Java process pertaining to the SpringBoot application uses the real path of jars as the classpath arg. In other words, the temp directory `/var/folders/...` (which contains jar files) is a symlink and resolves to `/private/var/folders/...` on MacOS. We might use the real path instead of the absolute path and then compare the args.

### Eclipse JKube version

SNAPSHOT

### Component

JKube Kit

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

1. It requires MacOS
2. Run tests from `SpringBootWatcherIntegrationTest` inside `jkube-jit module`
3. Observe the error

### Expected behavior

Tests inside SpringBootWatcherIntegrationTest should pass on MacOS as well as Linux.

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3

### Environment

macOS

### Eclipse JKube Logs

_No response_

### Sample Reproducer Project

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arman-yekkehkhani**
## Description
In order to fix failing tests on macos, we need to use the real path of jars instead of the absolute path. I.e. we need to use `private/var/folders/...` instead of `/var/folders/...`. Thus, method `absolutePath` is replaced with the `realPath`.

Fixes #3009 

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

File: jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java [hunk 1]
```diff
@@ -129,15 +130,19 @@ void withAllRequirementsShouldStartWatcherProcess() throws Exception {
...
+      realPath("spring-boot-lib.jar") + File.pathSeparator + realPath("spring-boot-devtools.jar"))
       && command[3].equals("-Dspring.devtools.remote.secret=this-is-a-test")
       && command[4].equals("org.springframework.boot.devtools.RemoteSpringApplication")
       && command[5].matches("^http://localhost:\\d+$")
     ));
   }
 
-  private String absolutePath(String jar) {
-    return project.resolve("target").resolve(jar).toFile().getAbsolutePath();
+  private String realPath(String jar) {
```
Comment (rohanKanojia) [inline jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java:140]: is it possible to inline this?

Comment (arman-yekkehkhani) [reply jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java:140]: I don't know how that would help. But the problem is that method `Path.toRealPath` throws an IO exception, and inlining the method can make handling the error a bit harder and the code less readable.

Comment (arman-yekkehkhani) [reply jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java:140]: @rohanKanojia Could you please explain what do you mean by inlining this method? because that does not look trivial to me

Comment (rohanKanojia) [reply jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java:140]: Sorry, I just saw your comment. This was just a nitpick. I think it's fine this way as well.

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!
