### PR TITLE
fix(docker-build): Ensure Docker build arguments from properties are used during images pre-pulling

### LINKED ISSUE #2901: Build Failure When Injecting Docker Build Args into Dockerfile 'FROM' Statement
### Describe the bug

According to the documentation on https://eclipse.dev/jkube/docs/kubernetes-maven-plugin/#property-buildargs, it should be possible to pass build arguments from properties using the format: `<docker.buildArg.myBuildArg>myValue</docker.buildArg.myBuildArg>`. This method functions correctly except when the build arguments are used within the 'FROM' statement of a Dockerfile. In such cases, JKube attempts to pre-pull the image without incorporating the specified build arguments, leading to a failure in the build process.

### Eclipse JKube version

1.16.2

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

1. **Prepare the Dockerfile**:
   Save the following content in `src/main/docker/Dockerfile`:

   ```dockerfile
   ARG IMAGEVERSION
   FROM docker.io/alpine:${IMAGEVERSION} as builder
   ARG IMAGEVERSION
   RUN touch test-${IMAGEVERSION}.txt

   FROM docker.io/alpine:${IMAGEVERSION}
   COPY --from=builder /test-${IMAGEVERSION}.txt /test.txt

   ENTRYPOINT ["ls"]
   ```

2. **Configure JKube Plugin in `pom.xml`**:
   Add the JKube Kubernetes Maven plugin configuration to your `pom.xml`:

   ```xml
   <plugin>
       <groupId>org.eclipse.jkube</groupId>
       <artifactId>kubernetes-maven-plugin</artifactId>
       <version>1.16.2</version>
       <configuration>
         <buildStrategy>docker</buildStrategy>
         <images>
           <image>
             <name>helloworld:%l</name>
             <build>
               <contextDir>${project.basedir}/src/main/docker/</contextDir>
               <dockerFile>Dockerfile</dockerFile>
             </build>
           </image>
         </images>
       </configuration>
   </plugin>
   ```

3. **Define Build Argument in `pom.xml`**:
   Specify the Docker build argument for the image version:

   ```xml
   <properties>
       <docker.buildArg.IMAGEVERSION>latest</docker.buildArg.IMAGEVERSION>
   </properties>
   ```

4. **Execute the Build**:
   Run the following command in your project directory:

   ```
   mvn k8s:build
   ```

5. **Observe the Error**:
   The build fails with the following error message:

   ```
   [ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.17-SNAPSHOT:build (default-cli) on project jkube-maven-sample-node-selector: Failed to execute the build: Error while trying to build the image: Unable to check image [docker.io/alpine:${IMAGEVERSION}] : {"message":"invalid reference format"} (Bad Request: 400) -> [Help 1]
   ```

### Expected behavior

The build should complete without errors

### Runtime

other (please specify in additional context)

### Kubernetes API Server version

1.25.3

### Environment

Linux

### Eclipse JKube Logs

_No response_

### Sample Reproducer Project

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sunix**
## Description

Fixes #2901 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Review by manusa — CHANGES_REQUESTED** [review]
I'd add a few more tests to demonstrate the precedence of the build args, properties, and so on.

For example, it's unclear to me right now if I supply a property and a build arg, which one will take precedence.

**Comment by sunix** [comment]
> I'd add a few more tests to demonstrate the precedence of the build args, properties, and so on.
> 
> For example, it's unclear to me right now if I supply a property and a build arg, which one will take precedence.

OK but I see that more like an enhancement than a bug fix, is the precedence of the build args documented ?

**Comment by manusa** [comment]
> > I'd add a few more tests to demonstrate the precedence of the build args, properties, and so on.
> > For example, it's unclear to me right now if I supply a property and a build arg, which one will take precedence.
> 
> OK but I see that more like an enhancement than a bug fix, is the precedence of the build args documented ?

No idea, but given that we are implementing new tests, it'd be nice to have that as part of the testing suite.
We'd basically need to maintain whatever precedence we have now. Considering you've moved the logic to merge args, properties, and so on. This was probably one of the first tests you should have implemented in order to ensure nothing breaks (a test that passes before and after your changes with the precedence).

File: jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java [hunk 1]
```diff
@@ -292,7 +298,7 @@ private boolean checkForNocache(ImageConfiguration imageConfig) {
         }
     }
 
-    private boolean isEmpty(String str) {
+    private static boolean isEmpty(String str) {
```
Comment (rohanKanojia) [inline jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java:301]: Maybe this can be replaced by [StringUtils.isBlank](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-)

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java [hunk 2]
```diff
@@ -93,4 +105,186 @@ void tagImage_whenValidImageConfigurationProvided_shouldTagImage() throws Docker
         .tag("image-name", "image-name:latest", true);
   }
 
+  @Test
+  void mergeBuildArgs_whenBuildArgsFromImageConfigAndFromProjectProperties_shouldMergeBuildArgs() {
```
Comment (rohanKanojia) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java:109]: maybe all `mergeBuildArgs_*` tests can be moved into a `@Nested` test class? Maybe these tests can share common code in `// Given` block in `@BeforeEach`?

Comment (sunix) [reply jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java:111]: I have refactored a bit, let me know if it is better or not

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java [hunk 3]
```diff
@@ -93,4 +107,171 @@ void tagImage_whenValidImageConfigurationProvided_shouldTagImage() throws Docker
...
+    props.setProperty("docker.buildArg.REPO_1", "docker.io/library");
+    props.setProperty("docker.buildArg.IMAGE-1", "openjdk");
+    when(mockedJKubeConfiguration.getProject().getProperties()).thenReturn(props);
+
+    // When
+    buildService.buildImage(imageConfiguration, mockedImagePullManager, mockedJKubeConfiguration);
+
+    // Then
+    // verify that the image "fabric8/s2i-java:latest", "busybox:latest",
+    // "docker.io/library/openjdk:latest" are prepulled
```
Comment (rohanKanojia) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java:260]:
```suggestion
```

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java [hunk 4]
```diff
@@ -93,4 +107,167 @@ void tagImage_whenValidImageConfigurationProvided_shouldTagImage() throws Docker
...
+    private void givenBuildArgsFromProjectProperties(String key, String value) {
+      Properties props = new Properties();
+      props.setProperty(key, value);
+      when(mockedJKubeConfiguration.getProject().getProperties()).thenReturn(props);
+    }
+
+    private void givenBuildArgsFromJKubeConfiguration(String key, String value) {
+      Map<String, String> jkubeConfigBuildArg = new HashMap<>();
+      jkubeConfigBuildArg.put(key, value);
+      when(mockedJKubeConfiguration.getBuildArgs()).thenReturn(jkubeConfigBuildArg);
```
Comment (rohanKanojia) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java:221]: nitpick, since there is only single entry in map... maybe we can use `Collections.singletonMap(key, value)` here?

File: jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java [hunk 5]
```diff
@@ -93,4 +107,167 @@ void tagImage_whenValidImageConfigurationProvided_shouldTagImage() throws Docker
...
+      // When & Then
+      assertThatIllegalArgumentException()
+          .isThrownBy(() -> BuildService.mergeBuildArgs(imageConfiguration, mockedJKubeConfiguration))
+          .withMessage("Multiple entries with same key: VERSION=latest and VERSION=1.0.0");
+    }
+
+    private void givenBuildArgsFromImageConfiguration(String key, String value) {
+      Map<String, String> imgConfigBuildArg = new HashMap<>();
+      imgConfigBuildArg.put(key, value);
+      imageConfiguration = ImageConfiguration.builder()
```
Comment (rohanKanojia) [inline jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java:200]: nitpick, since there is only single entry in map... maybe we can use `Collections.singletonMap(key, value)` here?

File: jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java [hunk 6]
```diff
@@ -194,24 +200,23 @@ private Map<String, String> addBuildArgs(JKubeConfiguration configuration) {
...
                     buildArgs.put(argKey, value);
                 }
             }
         }
-        log.debug("Build args set %s", buildArgs);
         return buildArgs;
     }
 
-    private Map<String, String> addBuildArgsFromDockerConfig() {
+    private static Map<String, String> addBuildArgsFromDockerConfig() {
```
Comment (rohanKanojia) [inline jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java:219]: After revisiting this PR from https://github.com/eclipse-jkube/jkube/issues/2904 's perspective, I have a feeling that maybe it would be better if all build arg related methods could be moved to a new class `BuildArgUtil` or `BuildArgResolver` . This way we will be able to use this from OpenShiftBuildService as well.

Comment (sunix) [reply jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java:219]: Yes I would leave it like that to keep it Small and Simple. And maybe have a dedicated PR for a refactor. WDYT ?

Comment (rohanKanojia) [reply jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java:219]: yeah, maybe better to do it in a follow up PR

**Review by manusa — APPROVED** [review]
LGTM, thx!
