### PR TITLE
fix (jkube-kit) : Sanitize VCS remote URL used in `jkube.eclipse.org/git-url` annotation

### LINKED ISSUE #2662: Sanitize VCS remote URL
## Description

Seen in https://github.com/quarkusio/quarkus/issues/38055

We're very likely affected by the same problem.

VCS URLs should be sanitized before persisted.

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #2662

Sanitize Git Remote URL before adding it to Git annotations.

## Type of change

 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] My code follows the style guidelines of this project
 - [X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [X] I have performed a self-review of my code
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes
 - [X] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2831 (_2024-03-18T10:31:31Z_)

:gear: [JKube E2E Tests (8325057238)](https://github.com/jkubeio/ci/actions/runs/8325057238) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2831)](https://github.com/jkubeio/ci/actions/runs/8325057238/job/22777892078)

File: jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/GitUtil.java [hunk 1]
```diff
@@ -69,4 +72,34 @@ public static String getGitCommitId(Repository repository) throws GitAPIExceptio
         }
         return null;
     }
+
+    /**
+     * Sanitize Git Repository's remote URL, trims username and access token from URL.
+     * This is taken from <a href="https://github.com/dekorateio/dekorate/blob/5f4acbd5b28251d88209388b6f2e826f5a546102/core/src/main/java/io/dekorate/utils/Git.java#L134">Dekorate's Git utility class</a>
```
Comment (manusa) [inline jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/GitUtil.java:78]: I forgot to remove this.
We can change it after merge.

**Review by manusa — APPROVED** [review]
LGTM, thx!
